  linux-webkitgtk-analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter_inappwebview_linux_webkitgtk
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install WebKitGTK dev packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libjavascriptcoregtk-4.1-dev
      - run: flutter pub get
      - run: dart analyze --fatal-infos

  linux-webkitgtk-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter_inappwebview/example
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install WebKitGTK dev packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libjavascriptcoregtk-4.1-dev clang cmake ninja-build pkg-config
      - run: flutter pub get
      - run: flutter build linux --debug
